### ISSUE TITLE
Tipping after reconnection

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/jitsi-meet#213]
When the user has lost the connection and then rejoins, he will not be able to tip old messages in the chat only new ones (messages that appear after reconnecting).

![Знімок екрана 2020-08-28 о 1 21 08 пп](https://user-images.githubusercontent.com/69896204/91564990-2a045480-e94a-11ea-997f-33dad039822c.png)

I tested SH wallet 9302621 / v.0.3.2 on Chrome, Firefox and Brave browsers.

**Comment by venimus** [comment]
This will be challenging because the users are differentiated by some internal ID, and when they disconnect and reconnect they will have new ID, while the wallet address of the older one is lost

**Comment by mike-gusev-ae** [comment]
Also, when we reconnecting, our messages displays like them wrote somebody else

**Comment by mike-gusev-ae** [comment]
1) For tipping, on line 81, after  reconnection we dont have ak_address anymore, that's why we dont see tip button (for old messages)
![Screen Shot 2020-08-31 at 14 10 32](https://user-images.githubusercontent.com/67146735/91714166-cff6cf80-eb93-11ea-8f67-3819c0b5d3c8.png)
2) > Also, when we reconnecting, our messages displays like them wrote somebody else

This is because of chat logic. Like Ivaylo said, we use ID right now and after reconnect user get new ID.
![Screen Shot 2020-08-31 at 14 15 06](https://user-images.githubusercontent.com/67146735/91714453-75aa3e80-eb94-11ea-9f27-433a5ac03a7b.png)

**Comment by venimus** [comment]
There seems a lot of cases we need to think of and be covered. These would be caused by the fact that messages can not store the wallet address and the only way is to look from the list of current participants in the room. People written messages then left the room will lose their address and any rejoins will not be able to get it from anywhere, also the other major problem is that after rejoining the jitsi user is recreated and have new id.

So I suggest to "tag" the messages from users with wallet with a meta-data in the message body itself (like prefix it with [ak_address] or something) which we can use for the tip button and will be persisted in the chat history. We can also parse the message and strip that meta data when it is displayed in the template to not clutter the chat

**Comment by venimus** [comment]
Some edge-case Chat tip scenarios:
- guest: user that did not identified with wallet (no jwt) typed a name in prejoin
- fellow superhero: user joined the room with default name (i.e. prejoin is disabled on the server or the Recorder)
- identified: user that have identified with wallet (have jwt)
1. guest user types a name manually and joins a room without confirming the jwt (the popup is left aside)
	1.1 user post a message in chat - his message is not tippable, because do not have address
	1.2 The user identified with jwt after joining (confirms the previous popup) - his messages become tippble
	1.3 user posts second message
	1.4 The now identified user leaves the room
	1.5 Other users want to tip his old messages (his old messages should be tippble)
	1.6 User rejoins (gets a new jitsi ID) and identifies with the same wallet (address is the same but have new internal ID, so for jitsi chat he is a new user)
	1.7 User posts 3rd message (should be tippable because he identified with valid wallet)
	1.8 User leaves the room and do not rejoin
2. guest user fakes .chain name by manually typing it and there is already existing member that properly identified with the same .chain name but using jwt
	2.1 user posts message (his messages should not be tippable by others, as he have no real address)
	2.2 user then identifies with jwt and his display name changes to a valid .chain name (his message from 2.1 becomes tippable)
3. user identified with wallet on prejoin
	3.1 User sees old messages from previous steps (should be able to tip only the valid messages)
	3.1 user posts a message (should be tippable)
	3.2 user leaves the room (his old message should stay tippable)
	3.3 user joins again with the same wallet id (but gets a new Jitsi ID) and posts new message (it should be tippable as well as the old one)
	3.4 user should be able to tip all valid messages in chat (including the ones from other users no longer exist in the room)
4. several users joins as Fellow superhero (or with the same name i.e. test or Nikita for instance)
	4.1 they post messages in chat (appearing with the same name)
	4.2 one of the users refresh the page (try to rejoin)
	4.3 he identifies in the prejoin screen using the wallet
	4.4 user joins now as identified user (his can no longer be connected to their old messages, so old messages stay untippable)
	4.5 user posts new message (only that should be tippable)
5. user identifies with jwt on prejoin
	5.1 user posts message (should be tippable)
	5.2 user leaves
	5.3 user joins with new wallet
	5.4 user posts new message (should be tippbable to the new address, old message tippble to old wallet)

**Comment by venimus** [comment]
however i think the workaround i suggested would cover the rejoin cases, exception will be messages that user posted without identification will stay untippable, because they won't be "tagged" with any address
