### ISSUE TITLE
Drop out of call when someone else joins

### ISSUE THREAD

**Issue by mradkov** [aeternity/jitsi-meet#23]

**Comment by venimus** [comment]
I think this was happening because the jitsi-videobride service wasn't running at that time for some reason. Jitsi have 3 modes of working that depend on different services and how many participants are in the call (1, 2 or 3 and more). If only 1 user there is no service responsible for audio/video, when 2 they start using P2P mode (i disabled that as being useless). When more users join then the jitsi-videobride service start handling the stream and if not running you will get dropouts.

I think that issue should be "resolved" now
